# Generated by Django 4.2.5 on 2024-03-16 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_purchase_seat_number_alter_ticket_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
