# Generated by Django 4.2.5 on 2024-03-19 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_purchase_student_discount_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=uuid.uuid4, max_length=32, unique=True),
        ),
    ]
