# Generated by Django 4.2.5 on 2024-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_student_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='number_of_tickets',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='student_discount',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='student_discount',
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_type',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('student', 'Student')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
    ]
