# Generated by Django 4.2.5 on 2024-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_purchase_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='concert',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tickets',
        ),
        migrations.AddField(
            model_name='purchase',
            name='tickets',
            field=models.JSONField(default=dict),
        ),
    ]
