# Generated by Django 4.2.5 on 2024-04-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_purchase_concert_remove_purchase_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
