# Generated by Django 4.2.5 on 2024-04-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_purchase_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
